apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test2-noargocd-gitops
  description: This is GitOps manifest for test2-noargocd   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: test2-noargocd
    janus-idp.io/tekton: test2-noargocd 
    backstage.io/kubernetes-id: test2-noargocd 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:test2-noargocd
